export const ACTION_TYPE = {
    ADD_TODO: 'ADD_TODO',
    UPDATE_TODO: 'UPDATE_TODO',
    DELETE_TODO: 'DELETE_TODO',
    CLICK_ITEM: 'CLICK_ITEM',
    SET_SELECTED_TODO: 'SET_SELECTED_TODO',
    SET_FILTER: 'SET_FILTER',
    UPDATE_EXISTING_TODO: 'UPDATE_EXISTING_TODO',
    CLEAR_COMPLETED: 'CLEAR_COMPLETED',
};