export const ACTION_TYPE = {
    ADD_TODO_REQUEST: 'ADD_TODO_REQUEST',
    ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
    ADD_TODO_FAILURE: 'ADD_TODO_FAILURE',

    LOAD_TODOS_REQUEST: 'LOAD_TODOS_REQUEST',
    LOAD_TODOS_SUCCESS: 'LOAD_TODOS_SUCCESS',
    LOAD_TODOS_FAILURE: 'LOAD_TODOS_FAILURE',

    DELETE_TODO_REQUEST: 'DELETE_TODO_REQUEST',
    DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
    DELETE_TODO_FAILURE: 'DELETE_TODO_FAILURE',

    EDIT_TODO_REQUEST: 'EDIT_TODO_REQUEST',
    EDIT_TODO_SUCCESS: 'EDIT_TODO_SUCCESS',
    EDIT_TODO_FAILURE: 'EDIT_TODO_FAILURE',

    CLICK_ITEM_REQUEST: 'CLICK_ITEM_REQUEST',
    CLICK_ITEM_FAILURE: 'CLICK_ITEM_FAILURE',
    CLICK_ITEM_SUCCESS: 'CLICK_ITEM_SUCCESS',



    // ADD_TODO: 'ADD_TODO',
    // UPDATE_TODO: 'UPDATE_TODO',
    // DELETE_TODO: 'DELETE_TODO',
    // CLICK_ITEM: 'CLICK_ITEM',
    SET_SELECTED_TODO: 'SET_SELECTED_TODO',
    // SET_FILTER: 'SET_FILTER',
    // UPDATE_EXISTING_TODO: 'UPDATE_EXISTING_TODO',
    // CLEAR_COMPLETED: 'CLEAR_COMPLETED',
};
